### ISSUE TITLE
Difusión

### ISSUE THREAD

**Issue by pablogsal** [PythonGranada/organization#1]
La difusión de la asociación es un tema importante para que el máximo de personas posible sepa de nosotros y lo que hacemos. En esta Issue hablaremos de métodos para conseguir este objetivo y de quien los llevará a cabo.

Tareas a realizar:
- [x] Establecer lista de métodos de difusión.
- [ ] Distribuir tareas entre colaboradores.
- [x] Ideas y sugerencias.

**Comment by pablogsal** [comment]
A la gente que esta en la Universidad: ¿Qué ideas se os ocurren para difundir la asociación?

**Comment by M42** [comment]
Ideas para la difusión:
 - [ ] Un par de **carteles** en ciencias e informática.
 - [ ] Contactar con **profesores** que quieran explicarlo a sus alumnos. Quizá usar los problemas del Python Kung-Fu, o explicar algorítmica con Python, y puedan recomendar la asociación.
 - [ ] Introducirlo especialmente a los de **primer año**. Que tuvieran algo que les hiciera empezar a programar en Python. (¿Un pequeño curso, quizá?)
 - [ ] Entre el doble grado, lo difundimos por la organización @dgiim.

**Comment by pablogsal** [comment]
Yo me ocupo de preparar la charla. Habría que hablar con alguien para que nos organice el asunto (un profesor, vaya). Intentaré hablar con Victor para ello.

**Comment by pablogsal** [comment]
He hablado con Evangelina para preparar una charla a los de primer año. Ha dicho que nos va a ayudar, pero hay que ultimar los detalles. Si necesito ayuda, lo comento por aquí.

**Comment by pablogsal** [comment]
Actualización:

-Mail enviado a Evangelina y conversación en marcha.

-Mail enviado a Andrés Roldán Aranda sin contestación aún.

**Comment by pablogsal** [comment]
Andrés Roldán Aranda comenta de hacer una charla en la Universidad hablando de nuestra asociación y de Python en General y aplicado a la electrónica. Quiere expedir certificados de asistencia, lo cual está muy bien. Sigo en contacto con el.
